apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  # The reason why we use NodePort is because we need it expose to run the migrations from prisma
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30052
