name: Build & Deploy Fast Food API

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  AWS_REGION: us-east-1
  IMAGE_NAME: cauakath/fast-food-tc
  TERRAFORM_DIR: terraform

jobs:
  build_and_push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    name: 🐳 Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

  terraform:
    name: ⚙️ Terraform Deploy
    runs-on: ubuntu-latest
    needs: build_and_push

    permissions:
      contents: read
      id-token: write

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform init -input=false -backend-config="envs/prod/backend.hcl"

      - name: Terraform Validate
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: |
          terraform plan -input=false \
            -var="aws_region=${{ env.AWS_REGION }}" \
            -var="db_username=${{ secrets.DB_USERNAME }}" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -var="mp_user=${{ secrets.MP_USER_ID }}" \
            -var="mp_client_id=${{ secrets.MP_CLIENT_ID }}" \
            -var="mp_client_secret=${{ secrets.MP_CLIENT_SECRET }}"

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: |
          terraform apply -input=false -auto-approve \
            -var="aws_region=${{ env.AWS_REGION }}" \
            -var="db_username=${{ secrets.DB_USERNAME }}" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -var="mp_user=${{ secrets.MP_USER_ID }}" \
            -var="mp_client_id=${{ secrets.MP_CLIENT_ID }}" \
            -var="mp_client_secret=${{ secrets.MP_CLIENT_SECRET }}"
